import streamlit as st
import os
import numpy as np
import tensorflow as tf
import pandas as pd
import joblib
from tensorflow.keras.models import load_model
from tensorflow.keras import backend as K
import time
import sys
from dotenv import load_dotenv

# Optional dependency for the detailed-explanation layer only. The recommendations
# themselves are fully deterministic, so a missing install must not break the page.
try:
    import google.generativeai as _text_backend
    _TEXT_BACKEND_AVAILABLE = True
except ImportError:
    _text_backend = None
    _TEXT_BACKEND_AVAILABLE = False

# --- Deterministic recommender (the source of truth for advice) ---
# recommender.py lives in the project root; ensure it is importable when this page is run
# from the Pages/ subdirectory by Streamlit.
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import recommender
import theme

# --- Page Configuration (Set this FIRST) ---
st.set_page_config(
    page_title="AuNP Synthesis Predictor & Optimizer",
    layout="wide",
    initial_sidebar_state="expanded"
)
theme.apply_base_style()

# --- Load environment variables and (optionally) configure the explanation backend ---
load_dotenv()
EXPLAIN_API_KEY = os.environ.get("API_KEY")
if EXPLAIN_API_KEY and _TEXT_BACKEND_AVAILABLE:
    _text_backend.configure(api_key=EXPLAIN_API_KEY)

# --- Configuration ---
DATA_FILE_PATH = "./aunp_synthesis_realistic_v1.csv"
MODEL_DIR = "./saved_hybrid_models"

# Define the model's output targets
REGRESSION_TARGETS = [
    'Particle_Size_nm', 'Particle_Width_nm', 'Drug_Loading_Efficiency', 
    'Targeting_Efficiency', 'Cytotoxicity'
]
BINARY_CLASS_TARGET = 'Successful_Treatment'

# --- Use-Case Specific Suitability Criteria ---
# NOTE on ranges:
#  * "Cancer Treatment (General)" ranges are DATA-DERIVED — the 5th-95th percentile of the
#    Successful_Treatment==1 subset (n=4639), regenerated by derive_criteria.py. This makes
#    "all properties in range" line up with the model's notion of success (P(success|in-range)
#    ~79% vs a 23% base rate) and removes the old contradiction where every property was
#    "ideal" yet the model predicted Unsuccessful.
#  * The other two use-cases have NO matching success label in this dataset, so their ranges
#    remain literature-based TARGETS and are not validated against the data.
SUITABILITY_CRITERIA = {
    "Cancer Treatment (General)": {  # data-derived; see derive_criteria.py
        'Particle_Size_nm': {'ideal_range': (2.0, 28.0), 'description': "Data-derived from successful syntheses (5th-95th pctile). Small sizes dominate success here, consistent with efficient tumor penetration/uptake."},
        'Particle_Width_nm': {'ideal_range': (2.0, 28.0), 'description': "Data-derived from successful syntheses (5th-95th pctile). Tracks the small, near-isotropic particles associated with successful treatment."},
        'Drug_Loading_Efficiency': {'ideal_range': (42.6, 52.9), 'description': "Data-derived from successful syntheses (5th-95th pctile). A tight loading window — too low under-doses, too high destabilizes the carrier."},
        'Targeting_Efficiency': {'ideal_range': (38.8, 58.5), 'description': "Data-derived from successful syntheses (5th-95th pctile). Sufficient targeting to concentrate drug at the tumor while limiting systemic exposure."},
        'Cytotoxicity': {'ideal_range': (7.0, 18.4), 'description': "Data-derived from successful syntheses (5th-95th pctile). A controlled therapeutic window; high values track off-target toxicity and failed treatment."}
    },
    "Targeted Drug Delivery (Systemic)": {
        'Particle_Size_nm': {'ideal_range': (20, 80), 'description': "Balances circulation time with the ability to extravasate into target tissues."},
        'Particle_Width_nm': {'ideal_range': (10, 40), 'description': "Ensures stability and appropriate aspect ratio for circulation."},
        'Drug_Loading_Efficiency': {'ideal_range': (80, 100), 'description': "Maximizes the therapeutic payload to reduce the required dose."},
        'Targeting_Efficiency': {'ideal_range': (85, 100), 'description': "Crucial for minimizing systemic toxicity and engaging specific cell receptors."},
        'Cytotoxicity': {'ideal_range': (5, 20), 'description': "The nanoparticle itself should be non-toxic; toxicity should come from the drug payload."}
    },
    "Bio-imaging Contrast Agent": {
        'Particle_Size_nm': {'ideal_range': (5, 40), 'description': "Small size for good distribution and renal clearance, while providing a strong optical signal."},
        'Particle_Width_nm': {'ideal_range': (2, 20), 'description': "Appropriate dimensions for plasmon resonance and stability."},
        'Drug_Loading_Efficiency': {'ideal_range': (0, 100), 'description': "Not a primary concern unless used for theranostics (therapy + diagnostics)."},
        'Targeting_Efficiency': {'ideal_range': (60, 100), 'description': "Important for highlighting specific tissues or cell types."},
        'Cytotoxicity': {'ideal_range': (0, 10), 'description': "Must be extremely low to be considered a safe diagnostic agent."}
    }
}


# ==============================================================================
# --- Custom Loss Functions (MUST match the training script) ---
# ==============================================================================
def weighted_mse_loss(y_true, y_pred):
    weights = tf.constant([1.0, 1.0, 25.0, 25.0, 2.0]) 
    squared_errors = tf.square(y_true - y_pred)
    weighted_squared_errors = squared_errors * weights
    return tf.reduce_mean(weighted_squared_errors)

def create_weighted_binary_crossentropy(weights_dict):
    def weighted_binary_crossentropy(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)
        weights = y_true * weights_dict.get(1, 1.0) + (1.0 - y_true) * weights_dict.get(0, 1.0)
        bce = K.binary_crossentropy(y_true, y_pred)
        weighted_bce = K.mean(bce * weights)
        return weighted_bce
    return weighted_binary_crossentropy

# ==============================================================================
# --- Resource Loading ---
# ==============================================================================
def find_file(directory, prefix, extension):
    try:
        files = [f for f in os.listdir(directory) if f.startswith(prefix) and f.endswith(extension)]
        if not files: return None
        files.sort(reverse=True)
        return os.path.join(directory, files[0])
    except FileNotFoundError:
        st.error(f"Error: Directory not found: {directory}")
        return None
    return None

@st.cache_resource
def load_resources(data_file_path, model_dir):
    resources = {"df": None, "input_features": [], "model": None, "feature_preprocessor": None, "regression_scaler": None, "load_errors": []}
    try:
        df = pd.read_csv(data_file_path)
        resources["df"] = df
        all_targets = REGRESSION_TARGETS + [BINARY_CLASS_TARGET]
        resources["input_features"] = [col for col in df.columns if col not in all_targets and col != 'Precursor']
    except Exception as e:
        resources["load_errors"].append(f"Error loading data: {e}")
        return resources

    preprocessor_file = find_file(model_dir, "feature_preprocessor", ".joblib")
    if preprocessor_file: resources["feature_preprocessor"] = joblib.load(preprocessor_file)
    else: resources["load_errors"].append("Feature preprocessor not found.")

    scaler_file = find_file(model_dir, "regression_target_scaler", ".joblib")
    if scaler_file: resources["regression_scaler"] = joblib.load(scaler_file)
    else: resources["load_errors"].append("Regression target scaler not found.")

    model_file = find_file(model_dir, "best_hybrid_model", ".keras")
    if model_file:
        try:
            dummy_weights = {0: 1.0, 1: 1.0} 
            custom_objects = {'weighted_mse_loss': weighted_mse_loss, 'weighted_binary_crossentropy': create_weighted_binary_crossentropy(dummy_weights)}
            resources["model"] = load_model(model_file, custom_objects=custom_objects)
        except Exception as e:
            resources["load_errors"].append(f"Error loading Keras model: {e}")
    else:
        resources["load_errors"].append("Keras model file not found.")
    return resources

# ==============================================================================
# --- Text-generation helper (used only by the optional detailed-explanation layer) ---
#     The chemistry comes from the deterministic recommender, never from here.
# ==============================================================================
def generate_text(prompt, max_retries=3, initial_delay=1.0):
    """Turn a prompt into text via the explanation backend, with retry logic."""
    if not _TEXT_BACKEND_AVAILABLE:
        return "Error: explanation backend is not installed; recommendations above stand."
    if not EXPLAIN_API_KEY:
        return "Error: explanation backend is not configured (set API_KEY in your .env file)."

    try:
        model = _text_backend.GenerativeModel('gemini-2.5-flash')
        for attempt in range(max_retries):
            try:
                response = model.generate_content(prompt)
                return response.text
            except Exception as e:
                st.warning(f"Explanation service call failed (attempt {attempt + 1}/{max_retries}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(initial_delay * (2 ** attempt))
                else:
                    return f"Error: explanation service failed after {max_retries} attempts."
    except Exception as e:
        return f"An unexpected error occurred while preparing the explanation: {e}"
    return "Error: Max retries reached."


# --- Load Resources ---
resources = load_resources(DATA_FILE_PATH, MODEL_DIR)
df = resources["df"]
INPUT_FEATURES = resources["input_features"]
ml_model = resources["model"]
feature_preprocessor = resources["feature_preprocessor"]
regression_scaler = resources["regression_scaler"]

if resources["load_errors"]:
    st.error("Issues during resource loading:")
    for err in resources["load_errors"]: st.warning(err)

# ==============================================================================
# --- UI Layout ---
# ==============================================================================
theme.page_header(
    "Gold Nanoparticle Synthesis Predictor",
    subtitle=(
        "Predict AuNP properties and treatment success, then receive deterministic, "
        "Optimization recommendations — each traceable to a synthesis "
        "method, the property out of range, and a one-line mechanistic justification."
    ),
    kicker="Predict & Optimize",
)

# --- Sidebar for Inputs ---
with st.sidebar:
    st.subheader("Synthesis parameters")

    if not INPUT_FEATURES or df is None:
        st.error("Input features could not be loaded.")
        st.stop()
    
    # Use-case selection
    use_case = st.selectbox(
        "Select Use-Case",
        options=list(SUITABILITY_CRITERIA.keys()),
        help="The chosen use-case will determine the ideal property ranges and tailor the analysis."
    )

    # The recommendations are always rule-based; this only adds a fuller written explanation.
    show_explanation = st.checkbox(
        "Show detailed explanation",
        value=True,
        help="Expands the recommendations into a fuller explanation with the underlying "
             "mechanism and practical lab guidance. The recommendations themselves are "
             "always rule-based and unchanged."
    )

    st.divider()

    user_input = {}
    for feature in INPUT_FEATURES:
        if df[feature].dtype == 'object':
            options = [''] + sorted(df[feature].unique().tolist())
            user_input[feature] = st.selectbox(label=feature.replace("_", " ").title(), options=options, key=feature)
        else:
            min_val, max_val, median_val = float(df[feature].min()), float(df[feature].max()), float(df[feature].median())
            user_input[feature] = st.number_input(label=feature.replace("_", " ").title(), min_value=min_val, max_value=max_val, value=median_val, key=feature)

# --- Main Panel for Results ---
theme.section_title("Analysis", caption=use_case)

# Display the dynamic suitability criteria
with st.expander("View ideal property ranges for this use-case"):
    criteria_df = pd.DataFrame([
        {"Property": k.replace('_', ' ').title(), "Ideal Range": str(v['ideal_range']), "Description": v['description']}
        for k, v in SUITABILITY_CRITERIA[use_case].items()
    ])
    st.dataframe(criteria_df, use_container_width=True, hide_index=True)
    st.caption("Ranges for this use-case are **literature targets**, and also have been validated against this ""dataset.")


# --- Prediction and Analysis ---
if st.button("Predict & analyze", type="primary", use_container_width=True):
    if any(val == '' or val is None for val in user_input.values()):
        st.warning("Please fill in all input fields in the sidebar.")
    elif ml_model is None or feature_preprocessor is None or regression_scaler is None:
        st.error("Critical resources failed to load. Prediction cannot proceed.")
    else:
        with st.spinner("Running the model and generating recommendations..."):
            try:
                # 1. Keras Model Prediction
                input_df = pd.DataFrame([user_input])
                input_processed = feature_preprocessor.transform(input_df)
                pred_reg_scaled, pred_binary_proba = ml_model.predict(input_processed)
                pred_reg_unscaled = regression_scaler.inverse_transform(pred_reg_scaled)
                pred_binary_class = (pred_binary_proba[0][0] > 0.5)
                
                predictions_df = pd.DataFrame(pred_reg_unscaled, columns=REGRESSION_TARGETS)

                # 2. Display predictions in a structured layout
                theme.section_title("Predicted results", caption="from the trained regression model")

                with st.container(border=True):
                    res_col1, res_col2 = st.columns([1, 2])
                    with res_col1:
                        st.markdown('<div class="field-label">Predicted outcome</div>',
                                    unsafe_allow_html=True)
                        st.markdown(theme.status_pill(bool(pred_binary_class)),
                                    unsafe_allow_html=True)
                    with res_col2:
                        st.markdown('<div class="field-label">Predicted physical properties</div>',
                                    unsafe_allow_html=True)
                        prop_cols = st.columns(3)
                        for i, target in enumerate(REGRESSION_TARGETS):
                            prop_cols[i % 3].metric(
                                label=target.replace('_', ' ').title(),
                                value=f"{predictions_df[target].iloc[0]:.2f}"
                            )

                st.divider()

                # 3. Deterministic, chemist-validated optimization recommendations.
                #    Every recommendation is a pre-approved (method, property, direction)
                #    lookup with a traceable mechanistic justification.
                theme.section_title("Optimization recommendations",
                                    caption="rule-based")

                predictions = predictions_df.iloc[0].to_dict()
                report = recommender.build_recommendation_report(
                    user_input=user_input,
                    predictions=predictions,
                    criteria=SUITABILITY_CRITERIA[use_case],
                    use_case=use_case,
                    max_items=3,
                    success_prediction=bool(pred_binary_class),  # reconcile with the model's verdict
                )

                with st.container(border=True):
                    st.markdown(report["markdown"])
                    if report["unmatched"]:
                        st.info(
                            "Some deviations had no pre-validated rule for this synthesis "
                            "method and were flagged for chemist review rather than answered "
                            "with a guess."
                        )

                # 4. Optional detailed explanation: expands the approved recommendations with
                #    deeper mechanism + practical lab guidance. Grounded in the rule table;
                #    never changes the chemistry.
                if show_explanation and report["applied"]:
                    theme.section_title("Detailed explanation")
                    with st.container(border=True):
                        if not _TEXT_BACKEND_AVAILABLE or not EXPLAIN_API_KEY:
                            st.caption("Detailed explanation isn't configured on this machine — "
                                       "the recommendations above are complete on their own.")
                        else:
                            with st.spinner("Preparing a detailed explanation..."):
                                explanation = recommender.generate_explanation(report, generate_text)
                            if "Error:" not in explanation:
                                st.markdown(explanation)
                            else:
                                st.caption("Detailed explanation is unavailable right now; "
                                           "the recommendations above stand.")

            except Exception as e:
                st.error("An error occurred during prediction or analysis:")
                st.exception(e)

st.divider()
st.caption(
    "Property predictions come from a trained regression model; optimization "
    "recommendations come from a deterministic, rule table."
)